name: Build

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Build
        env:
          TOKEN: ${{ secrets.GH_TOKEN_SCOPE_PACKAGES }}
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 5.7.1
          dotnet sonarscanner begin /k EffortGames_${{ github.event.repository.name }} /d . /o . /v 5.7.1 /sonar-project-name EffortGames_${{ github.event.repository.name }} /sonar-organization effortgames /s /dotnet 5.0.x
          dotnet nuget add source --username USERNAME --password "${TOKEN}" --store-password-in-clear-text --name github-effortgames "https://nuget.pkg.github.com/EffortGames/index.json"
          dotnet build .
          dotnet test .
          dotnet sonarscanner end /k EffortGames_${{ github.event.repository.name }} /d . /o . /v 5.7.1 /sonar-project-name EffortGames_${{ github.event.repository.name }} /sonar-organization effortgames /s /dotnet 5.0.x
